[package]
name = "qud"
version = "1.5.0"
edition = "2021"
license = "GPL-3"
authors = ["barely-a-dev"]

[dependencies]
colored = "3.0.0"
pico-args = { version = "0.5.0", features = ["combined-flags"] }
walkdir = "2.5.0"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3
