[package]
name = "qud"
version = "1.2.8"
edition = "2021"
license = "GPL-3"
authors = ["barely-a-dev"]

[dependencies]
pico-args = "0.5.0"
walkdir = "2.5.0"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3
